"""
PromptGuard – Global Settings
Centralised configuration loaded from environment variables with sensible defaults.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ── Load .env if present ────────────────────────────────────────────────────
load_dotenv()

# ── Base paths ───────────────────────────────────────────────────────────────
BASE_DIR: Path = Path(__file__).resolve().parents[2]   # project root: .../promptguard/

# ── Dataset paths ────────────────────────────────────────────────────────────
RAW_DATASET_PATH: Path = Path(
    os.getenv(
        "RAW_DATASET_PATH",
        str(BASE_DIR.parent / "PromptGuard" / "Dataset" / "PromptGuard_Dataset_FINAL.json"),
    )
)

PROCESSED_DATASET_PATH: Path = Path(
    os.getenv(
        "PROCESSED_DATASET_PATH",
        str(BASE_DIR / "data" / "processed" / "cleaned_dataset.jsonl"),
    )
)

# ── Logging ──────────────────────────────────────────────────────────────────
LOG_FILE_PATH: Path = Path(
    os.getenv("LOG_FILE_PATH", str(BASE_DIR / "logs" / "promptguard.log"))
)

# ── API settings ─────────────────────────────────────────────────────────────
API_TITLE: str = "PromptGuard"
API_VERSION: str = "0.4.0"
API_DESCRIPTION: str = (
    "Phase 4 – Rule + Semantic + DistilBERT + Aggregation + Decision Router "
    "adversarial prompt detection middleware."
)

# ── Risk thresholds (Phase 1) ─────────────────────────────────────────────────
RULE_BLOCK_SCORE: float = 1.0
RULE_ALLOW_SCORE: float = 0.0

# ── Phase 2: Semantic similarity settings ─────────────────────────────────────

# Risk score assigned when the semantic layer triggers a BLOCK.
# Intentionally lower than RULE_BLOCK_SCORE (1.0) to reflect that semantic
# similarity is probabilistic, not deterministic.
SEMANTIC_BLOCK_SCORE: float = 0.9

# Cosine similarity threshold above which a prompt is flagged as matching a
# known attack embedding.  Tune this after evaluating on your validation set.
SEMANTIC_MATCH_THRESHOLD: float = 0.65

# Paths for pre-built SBERT embeddings and FAISS index.
# These files are generated by the build scripts in scripts/.
EMBEDDINGS_PATH: str = str(BASE_DIR / "data" / "embeddings" / "attack_embeddings.npy")
FAISS_INDEX_PATH: str = str(BASE_DIR / "data" / "embeddings" / "faiss_index.bin")

# SBERT model name – change to swap backbone (all-MiniLM-L6-v2 is the default).
SBERT_MODEL_NAME: str = "sentence-transformers/all-MiniLM-L6-v2"

# ── Phase 3: DistilBERT Classifier settings ───────────────────────────────────

# Path to the locally trained fine-tuned DistilBERT model.
CLASSIFIER_MODEL_PATH: str = str(BASE_DIR / "models" / "distilbert_promptguard")

# Risk score assigned when the classifier layer triggers a BLOCK.
# Intentionally lower than SEMANTIC_BLOCK_SCORE (0.9) to reflect that
# the classifier is a probabilistic model, and rule/semantic matches are
# more deterministic indicators.
CLASSIFIER_BLOCK_SCORE: float = 0.8
