"""
PromptGuard – SQLAlchemy Models (Phase 5)

Tables:
  attack_logs      One row per /check_prompt call
  daily_summaries  Aggregated per-day statistics
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class AttackLog(Base):
    """
    Stores the full audit record for every prompt evaluation.

    Columns
    -------
    id                 Auto-incrementing primary key.
    prompt_text        The (possibly truncated) raw prompt.
    decision           Router decision: ALLOW | BLOCK | SANITIZE.
    triggered_layer    Which layer triggered the decision: rule / semantic /
                       classifier / aggregation / none.
    rule_score         Rule-engine match score (0.0 or 1.0).
    semantic_score     SBERT cosine similarity to nearest known attack.
    classifier_score   Raw DistilBERT adversarial probability.
    chunk_risk_score   Per-chunk adversarial probability.
    final_risk_score   Weighted aggregation of all scores.
    sanitized_flag     True when SANITIZE decision was taken.
    target_llm         Optional: downstream LLM this prompt was destined for.
    top_tokens         JSON array of top suspicious tokens (explainability).
    threat_stored      True when prompt embedding was added to FAISS index.
    timestamp          UTC time of the evaluation.
    """

    __tablename__ = "attack_logs"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    prompt_text     = Column(Text,    nullable=False)
    decision        = Column(String(20), nullable=False, index=True)
    triggered_layer = Column(String(50), nullable=True)
    rule_score      = Column(Float, nullable=True)
    semantic_score  = Column(Float, nullable=True)
    classifier_score = Column(Float, nullable=True)
    chunk_risk_score = Column(Float, nullable=True)
    final_risk_score = Column(Float, nullable=True)
    sanitized_flag  = Column(Boolean, default=False, nullable=False)
    target_llm      = Column(String(120), nullable=True)
    top_tokens      = Column(Text, nullable=True)    # JSON string
    threat_stored   = Column(Boolean, default=False, nullable=False)
    timestamp       = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )

    def __repr__(self) -> str:
        return (
            f"<AttackLog id={self.id} decision={self.decision!r} "
            f"triggered_layer={self.triggered_layer!r} "
            f"risk={self.final_risk_score:.4f} ts={self.timestamp}>"
        )


class DailySummary(Base):
    """
    Aggregated per-day statistics generated by the Celery beat scheduler.

    Columns
    -------
    date             ISO date string YYYY-MM-DD (unique index).
    total_requests   All /check_prompt calls on that day.
    blocked_count    BLOCK decisions.
    sanitized_count  SANITIZE decisions.
    allowed_count    ALLOW decisions.
    updated_at       When this row was last refreshed.
    """

    __tablename__ = "daily_summaries"
    __table_args__ = (UniqueConstraint("date", name="uq_daily_summaries_date"),)

    id              = Column(Integer, primary_key=True, autoincrement=True)
    date            = Column(String(10), nullable=False, index=True)
    total_requests  = Column(Integer, default=0)
    blocked_count   = Column(Integer, default=0)
    sanitized_count = Column(Integer, default=0)
    allowed_count   = Column(Integer, default=0)
    updated_at      = Column(DateTime(timezone=True), nullable=True)

    def __repr__(self) -> str:
        return (
            f"<DailySummary date={self.date} total={self.total_requests} "
            f"block={self.blocked_count} sanitize={self.sanitized_count} "
            f"allow={self.allowed_count}>"
        )
